services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: price_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
